import {
  Port,
  ShapeStyle,
  ShapeTypeDefinition,
} from "@diagram/core";
import { defaultShapeRegistry } from "@diagram/core";

const STANDARD_PORTS: Port[] = [
  { id: "top", x: 0.5, y: 0 },
  { id: "right", x: 1, y: 0.5 },
  { id: "bottom", x: 0.5, y: 1 },
  { id: "left", x: 0, y: 0.5 },
  { id: "center", x: 0.5, y: 0.5 },
];

const DEFAULT_STYLE: ShapeStyle = {
  fill: "#ffffff",
  stroke: "#1e293b",
  strokeWidth: 2,
  fontSize: 14,
  fontFamily: "system-ui, sans-serif",
  textColor: "#0f172a",
};

function defineShape(
  definition: Omit<ShapeTypeDefinition, "ports"> & { ports?: Port[] },
): ShapeTypeDefinition {
  return {
    ports: STANDARD_PORTS,
    defaultStyle: DEFAULT_STYLE,
    ...definition,
  };
}

export const builtinShapes: ShapeTypeDefinition[] = [
  defineShape({
    type: "rectangle",
    label: "Rectangle",
    category: "general",
    description: "Basic box for services, components, or notes",
    defaultWidth: 160,
    defaultHeight: 80,
  }),
  defineShape({
    type: "rounded-rectangle",
    label: "Rounded rectangle",
    category: "general",
    description: "Soft-corner box",
    defaultWidth: 160,
    defaultHeight: 80,
    defaultProps: { cornerRadius: 12 },
  }),
  defineShape({
    type: "ellipse",
    label: "Ellipse",
    category: "general",
    description: "Oval shape for events or states",
    defaultWidth: 120,
    defaultHeight: 80,
  }),
  defineShape({
    type: "diamond",
    label: "Diamond",
    category: "general",
    description: "Decision or gateway",
    defaultWidth: 120,
    defaultHeight: 120,
  }),
  defineShape({
    type: "parallelogram",
    label: "Parallelogram",
    category: "general",
    description: "Input/output or queue",
    defaultWidth: 160,
    defaultHeight: 80,
    defaultProps: { skew: 24 },
  }),
  defineShape({
    type: "cylinder",
    label: "Database",
    category: "data",
    description: "Database or persistent store",
    defaultWidth: 100,
    defaultHeight: 120,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#e0f2fe" },
  }),
  defineShape({
    type: "cloud",
    label: "Cloud",
    category: "infrastructure",
    description: "External system or cloud boundary",
    defaultWidth: 140,
    defaultHeight: 90,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#f8fafc" },
  }),
  defineShape({
    type: "hexagon",
    label: "Hexagon",
    category: "general",
    description: "Process or preparation step",
    defaultWidth: 120,
    defaultHeight: 100,
  }),
  defineShape({
    type: "document",
    label: "Document",
    category: "general",
    description: "Report, spec, or file artifact",
    defaultWidth: 120,
    defaultHeight: 100,
  }),
  defineShape({
    type: "actor",
    label: "Actor",
    category: "uml",
    description: "Person or external actor",
    defaultWidth: 60,
    defaultHeight: 100,
    ports: [
      { id: "top", x: 0.5, y: 0.1 },
      { id: "right", x: 0.9, y: 0.45 },
      { id: "bottom", x: 0.5, y: 0.9 },
      { id: "left", x: 0.1, y: 0.45 },
      { id: "center", x: 0.5, y: 0.45 },
    ],
  }),
  defineShape({
    type: "container",
    label: "Container",
    category: "layout",
    description: "Grouping boundary for subsystems",
    defaultWidth: 320,
    defaultHeight: 240,
    defaultStyle: {
      ...DEFAULT_STYLE,
      fill: "transparent",
      stroke: "#94a3b8",
      strokeWidth: 2,
    },
    defaultProps: { dashed: true },
  }),
  defineShape({
    type: "text",
    label: "Text",
    category: "annotation",
    description: "Standalone label",
    defaultWidth: 160,
    defaultHeight: 40,
    defaultStyle: { ...DEFAULT_STYLE, fill: "transparent", stroke: "transparent" },
  }),
  defineShape({
    type: "freehand",
    label: "Freehand",
    category: "annotation",
    description: "Vector freehand stroke",
    defaultWidth: 120,
    defaultHeight: 80,
    ports: [{ id: "center", x: 0.5, y: 0.5 }],
    defaultProps: { points: [] },
    defaultStyle: {
      ...DEFAULT_STYLE,
      fill: "transparent",
      stroke: "#1e293b",
      strokeWidth: 3,
    },
  }),
  defineShape({
    type: "server",
    label: "Server",
    category: "tech",
    description: "Application or compute server",
    defaultWidth: 90,
    defaultHeight: 110,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#f1f5f9" },
  }),
  defineShape({
    type: "api-gateway",
    label: "API Gateway",
    category: "tech",
    description: "API gateway or load balancer",
    defaultWidth: 120,
    defaultHeight: 80,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#ede9fe" },
  }),
  defineShape({
    type: "queue",
    label: "Queue",
    category: "tech",
    description: "Message queue or event bus",
    defaultWidth: 120,
    defaultHeight: 70,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#fef3c7" },
  }),
  defineShape({
    type: "client",
    label: "Client",
    category: "tech",
    description: "Browser, mobile app, or end-user client",
    defaultWidth: 100,
    defaultHeight: 80,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#f8fafc" },
  }),
  defineShape({
    type: "terminator",
    label: "Start / End",
    category: "flow",
    description: "Flowchart start or end node",
    defaultWidth: 140,
    defaultHeight: 56,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#ecfdf5" },
  }),
  defineShape({
    type: "flow-start",
    label: "Start",
    category: "flow",
    description: "Flowchart start node",
    defaultWidth: 140,
    defaultHeight: 56,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#ecfdf5" },
  }),
  defineShape({
    type: "flow-end",
    label: "End",
    category: "flow",
    description: "Flowchart end node",
    defaultWidth: 140,
    defaultHeight: 56,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#fce7f3" },
  }),
  defineShape({
    type: "flow-delay",
    label: "Delay",
    category: "flow",
    description: "Delay or wait step",
    defaultWidth: 120,
    defaultHeight: 60,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#fff7ed" },
  }),
  defineShape({
    type: "flow-manual-input",
    label: "Manual input",
    category: "flow",
    description: "Manual input step",
    defaultWidth: 140,
    defaultHeight: 70,
    defaultProps: { skew: 20 },
    defaultStyle: { ...DEFAULT_STYLE, fill: "#fefce8" },
  }),
  defineShape({
    type: "off-page-connector",
    label: "Off-page",
    category: "flow",
    description: "Connector to another page",
    defaultWidth: 80,
    defaultHeight: 60,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#f1f5f9" },
  }),
  defineShape({
    type: "uml-class",
    label: "Class",
    category: "uml",
    description: "UML class with compartments",
    defaultWidth: 160,
    defaultHeight: 120,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#fdf4ff" },
  }),
  defineShape({
    type: "uml-use-case",
    label: "Use case",
    category: "uml",
    description: "UML use case",
    defaultWidth: 140,
    defaultHeight: 80,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#f0f9ff" },
  }),
  defineShape({
    type: "uml-component",
    label: "Component",
    category: "uml",
    description: "UML component",
    defaultWidth: 140,
    defaultHeight: 90,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#f8fafc" },
  }),
  defineShape({
    type: "uml-interface",
    label: "Interface",
    category: "uml",
    description: "UML interface (lollipop)",
    defaultWidth: 120,
    defaultHeight: 40,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#ffffff" },
  }),
  defineShape({
    type: "uml-package",
    label: "Package",
    category: "uml",
    description: "UML package container",
    defaultWidth: 180,
    defaultHeight: 120,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#fafafa" },
  }),
  defineShape({
    type: "uml-state",
    label: "State",
    category: "uml",
    description: "UML state node",
    defaultWidth: 140,
    defaultHeight: 70,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#eff6ff" },
  }),
  defineShape({
    type: "uml-object",
    label: "Object",
    category: "uml",
    description: "UML object instance",
    defaultWidth: 140,
    defaultHeight: 80,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#ffffff" },
  }),
  defineShape({
    type: "uml-note",
    label: "Note",
    category: "uml",
    description: "UML note or comment",
    defaultWidth: 120,
    defaultHeight: 90,
    defaultStyle: { ...DEFAULT_STYLE, fill: "#fffbeb" },
  }),
  defineShape({
    type: "uml-seq-participant",
    label: "Participant",
    category: "uml",
    description: "UML sequence diagram participant with lifeline",
    defaultWidth: 120,
    defaultHeight: 400,
    defaultProps: { headerHeight: 48, actor: false },
    defaultStyle: { ...DEFAULT_STYLE, fill: "#dbeafe" },
  }),
  defineShape({
    type: "uml-seq-activation",
    label: "Activation",
    category: "uml",
    description: "UML sequence activation bar",
    defaultWidth: 10,
    defaultHeight: 80,
    defaultStyle: {
      ...DEFAULT_STYLE,
      fill: "#60a5fa",
      stroke: "#2563eb",
      strokeWidth: 1.5,
    },
  }),
  defineShape({
    type: "uml-seq-message",
    label: "Message",
    category: "uml",
    description: "UML sequence message arrow",
    defaultWidth: 160,
    defaultHeight: 28,
    defaultProps: { horizontal: true, return: false, lineStyle: "solid" },
    defaultStyle: { ...DEFAULT_STYLE, fill: "transparent", stroke: "#1e293b" },
  }),
  defineShape({
    type: "arrow-line",
    label: "Arrow line",
    category: "general",
    description: "Pointed line with arrowhead",
    defaultWidth: 120,
    defaultHeight: 80,
    defaultProps: { return: false, lineStyle: "solid" },
    defaultStyle: { ...DEFAULT_STYLE, fill: "transparent", stroke: "#1e293b" },
  }),
];

export function registerBuiltinShapes(
  registry = defaultShapeRegistry,
): typeof registry {
  for (const shape of builtinShapes) {
    if (!registry.get(shape.type)) {
      registry.register(shape);
    }
  }
  return registry;
}

registerBuiltinShapes();
